//
//  MonthTableRouter.swift
//  ajwa
//
//  Created by Adlet Zhantassov on 28.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MonthTableRoutingLogic {
    
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    
}

protocol MonthTableDataPassing {
    
  var dataStore: MonthTableDataStore? { get }
    
}

class MonthTableRouter: NSObject, MonthTableRoutingLogic, MonthTableDataPassing {
    
  weak var viewController: MonthTableViewController?
  var dataStore: MonthTableDataStore?
  
}
