//
//  MonthTablePresenter.swift
//  ajwa
//
//  Created by Adlet Zhantassov on 28.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MonthTablePresentationLogic
{
  func presentSomething(response: MonthTable.Something.Response)
}

class MonthTablePresenter: MonthTablePresentationLogic
{
  weak var viewController: MonthTableDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MonthTable.Something.Response)
  {
    let viewModel = MonthTable.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
