//
//  MonthTableInteractor.swift
//  ajwa
//
//  Created by Adlet Zhantassov on 28.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MonthTableBusinessLogic {
    func loadData()
}

protocol MonthTableDataStore {
  //var name: String { get set }
}

class MonthTableInteractor: MonthTableBusinessLogic, MonthTableDataStore {
  var presenter: MonthTablePresentationLogic?
  var worker: MonthTableWorker?
  var data: ZeekrModel?
  
  // MARK: Do something
  
    func loadData() {
        guard let url = URL(string: "https://api.muftyat.kz/prayer-times/2022/51.133333/71.433333?format=json") else { fatalError("Invalid URL") }
        
        NetworkManager.shared.getRequest(fromURL: url) { (result: Result<ZeekrModel, Error>) in
            switch result {
            case .success(let data):
                self.presenter?.transformData(data: data)
            case .failure(let error):
                print("we got error description: \(error.localizedDescription)")
            }
        }
    }
}
