//
//  MonthTableInteractor.swift
//  ajwa
//
//  Created by Adlet Zhantassov on 28.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MonthTableBusinessLogic
{
  func doSomething(request: MonthTable.Something.Request)
}

protocol MonthTableDataStore
{
  //var name: String { get set }
}

class MonthTableInteractor: MonthTableBusinessLogic, MonthTableDataStore
{
  var presenter: MonthTablePresentationLogic?
  var worker: MonthTableWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MonthTable.Something.Request)
  {
    worker = MonthTableWorker()
    worker?.doSomeWork()
    
    let response = MonthTable.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
