//
//  MonthTableModels.swift
//  ajwa
//
//  Created by Adlet Zhantassov on 28.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MonthTable {
  
  enum Something {
      
    struct Request {
        
    }
      
    struct Response {
        
    }
      
    struct ViewModel {
        
    }
  }
}
