//
//  FontSettingsPresenter.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 09.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FontSettingsPresentationLogic
{
  func presentSomething(response: FontSettings.Something.Response)
}

class FontSettingsPresenter: FontSettingsPresentationLogic
{
  weak var viewController: FontSettingsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FontSettings.Something.Response)
  {
    let viewModel = FontSettings.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
