//
//  FontSettingsConfigurator.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 09.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class FontSettingsConfigurator {
    
    static let shared = FontSettingsConfigurator()
    
    func configure(viewController: FontSettingsViewController) {
        let interactor = FontSettingsInteractor()
        let presenter = FontSettingsPresenter()
        let router = FontSettingsRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
    }
}
