//
//  FontSettingsViewController.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 09.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FontSettingsDisplayLogic: AnyObject
{
  func displaySomething(viewModel: FontSettings.Something.ViewModel)
}

class FontSettingsViewController: UIViewController, FontSettingsDisplayLogic
{
  var interactor: FontSettingsBusinessLogic?
  var router: (NSObjectProtocol & FontSettingsRoutingLogic & FontSettingsDataPassing)?
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = FontSettings.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: FontSettings.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
