//
//  FontSettingsInteractor.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 09.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FontSettingsBusinessLogic
{
  func doSomething(request: FontSettings.Something.Request)
}

protocol FontSettingsDataStore
{
  //var name: String { get set }
}

class FontSettingsInteractor: FontSettingsBusinessLogic, FontSettingsDataStore
{
  var presenter: FontSettingsPresentationLogic?
  var worker: FontSettingsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FontSettings.Something.Request)
  {
    worker = FontSettingsWorker()
    worker?.doSomeWork()
    
    let response = FontSettings.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
