//
//  FontSettingsInteractor.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 09.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FontSettingsBusinessLogic {
    func getFonts()
}

protocol FontSettingsDataStore {}

final class FontSettingsInteractor: FontSettingsBusinessLogic, FontSettingsDataStore {
    var presenter: FontSettingsPresentationLogic?
    var worker: FontSettingsWorker?
    var fonts = [FontSettings.ModelType.ViewModel]()

    // MARK: Do something

    func getFonts() {
        worker = FontSettingsWorker()
        self.presenter?.presentFonts(response: worker?.fetchFonts() ?? [])
    }
}
