//
//  PrayerTimePresenter.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 10.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PrayerTimePresentationLogic{
  func presentSomething(response: PrayerTime.Something.Response)
}

class PrayerTimePresenter: PrayerTimePresentationLogic{
  weak var viewController: PrayerTimeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PrayerTime.Something.Response){
    let viewModel = PrayerTime.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
