//
//  PrayerTimeConfigurator.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 10.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PrayerTimeConfigurator {
    
    static let shared = PrayerTimeConfigurator()
    
    func configure(viewController: PrayerTimeViewController) {
        let interactor = PrayerTimeInteractor()
        let presenter = PrayerTimePresenter()
        let router = PrayerTimeRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
    }
}
