//
//  PrayerTimeInteractor.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 10.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PrayerTimeBusinessLogic{
  func doSomething(request: PrayerTime.Something.Request)
}

protocol PrayerTimeDataStore{
  //var name: String { get set }
}

class PrayerTimeInteractor: PrayerTimeBusinessLogic, PrayerTimeDataStore{
  var presenter: PrayerTimePresentationLogic?
  var worker: PrayerTimeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: PrayerTime.Something.Request){
    worker = PrayerTimeWorker()
    worker?.doSomeWork()
    
    let response = PrayerTime.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
