//
//  PrayerTimeViewController.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 10.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PrayerTimeDisplayLogic: AnyObject{
  func displaySomething(viewModel: PrayerTime.Something.ViewModel)
}

class PrayerTimeViewController: UIViewController, PrayerTimeDisplayLogic{
  var interactor: PrayerTimeBusinessLogic?
  var router: (NSObjectProtocol & PrayerTimeRoutingLogic & PrayerTimeDataPassing)?
  
  // MARK: View lifecycle
  
  override func viewDidLoad(){
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething(){
    let request = PrayerTime.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: PrayerTime.Something.ViewModel){
    //nameTextField.text = viewModel.name
  }
}
