//
//  PrayerTimeInteractor.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 10.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PrayerTimeBusinessLogic{
  func getPrayers()
}

protocol PrayerTimeDataStore{
  //var name: String { get set }
}

class PrayerTimeInteractor: PrayerTimeBusinessLogic, PrayerTimeDataStore{
  var presenter: PrayerTimePresentationLogic?
  var worker: PrayerTimeWorker?
  //var name: String = ""
  
  // MARK: Do something
  
    func getPrayers() {
        worker = PrayerTimeWorker()
        self.presenter?.presentPrayers(response: worker?.fetchPrayerTimes() ?? [])
    }
}
