//
//  PrayerTimeWorker.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 10.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class PrayerTimeWorker{
    func fetchPrayerTimes() -> [PrayerTimes.ModelType.ViewModel] {
        let prayers = [
            PrayerTimes.ModelType.ViewModel(prayerName: "Фаджр", choosenMinute: 60),
            PrayerTimes.ModelType.ViewModel(prayerName: "Восход"),
            PrayerTimes.ModelType.ViewModel(prayerName: "Зухр"),
            PrayerTimes.ModelType.ViewModel(prayerName: "Аср"),
            PrayerTimes.ModelType.ViewModel(prayerName: "Магриб"),
            PrayerTimes.ModelType.ViewModel(prayerName: "Иша"),
        ]
        return prayers
    }
}
