//
//  ZeekrPresenter.swift
//  ajwa
//
//  Created by Adlet Zhantassov on 22.10.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ZeekrPresentationLogic {
  func presentData(data: ZeekrModel)
}

class ZeekrPresenter: ZeekrPresentationLogic {
    
  weak var viewController: ZeekrDisplayLogic?
  
  // MARK: Do something
  
  func presentData(data: ZeekrModel) {
    viewController?.updateInterface(data: data)
  }
    
}
