//
//  ZeekrModels.swift
//  ajwa
//
//  Created by Adlet Zhantassov on 22.10.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Zeekr {
    
  // MARK: Use cases
  
  enum Something {
      
    struct Request {
        
    }
      
    struct Response {
        
    }
      
    struct ViewModel {
        
    }
      
  }
}

// MARK: - Student

struct ZeekrModel: Codable {
    let city: String
    let result: [ResultModel]
    let success: Bool
    let year: Int
    let latitude, longitude: String
}

// MARK: - Result

struct ResultModel: Codable {
    let asr, date, maghrib, midnight: String
    let fajr, sunrise, sunset, isha: String
    let imsak, dhuhr: String

    enum CodingKeys: String, CodingKey {
        case asr
        case date = "Date"
        case maghrib, midnight, fajr, sunrise, sunset, isha, imsak, dhuhr
    }
}

struct ZeekrModelFiltered {
    
}
