//
//  ZeekrViewController.swift
//  ajwa
//
//  Created by Adlet Zhantassov on 22.10.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ZeekrDisplayLogic: AnyObject {
    
  func updateInterface(data: ZeekrModel)
    
}

class ZeekrViewController: UIViewController, ZeekrDisplayLogic {
    
  var interactor: ZeekrBusinessLogic?
  var router: (NSObjectProtocol & ZeekrRoutingLogic & ZeekrDataPassing)?
  var zeekrView = ZeekrView()
  
  // MARK: View lifecycle
    
    override func loadView() {
        view = zeekrView
    }
  
  override func viewDidLoad() {
      
    super.viewDidLoad()
    setupNavigation()
      
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
    
  func setupNavigation() {
        title = "Зикры"
  }
  
    func updateInterface(data: ZeekrModel) {
        
    }
}
