//
//  LanguagesWorker.swift
//  ajwa
//
//  Created by Aisaule Sibatova on 16.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LanguagesWorker
{
    func fetchLanguages(data: [Languages.Something.ViewModel]) -> [Languages.Something.ViewModel]
  {
      var languages = 
      
//      languages.append(Languages(languageTitle: "English"))
      
      return languages
      
  }
}
