//
//  LanguagesInteractor.swift
//  ajwa
//
//  Created by Aisaule Sibatova on 16.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol LanguagesBusinessLogic {
    func getLanguages()
}

protocol LanguagesDataStore {}

final class LanguagesInteractor: LanguagesBusinessLogic, LanguagesDataStore {
    var presenter: LanguagesPresentationLogic?
    var worker: LanguagesWorker?
    var languages = [Languages.ModelType.ViewModel]()
    
    // MARK: Do something
    
    func getLanguages() {
        worker = LanguagesWorker()
        self.presenter?.presentLanguages(response: worker?.fetchLanguages() ?? [])
    }
}
