//
//  EditProfileInteractor.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 10.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EditProfileBusinessLogic{
    func doSomething(request: EditProfile.Something.Request)
}

protocol EditProfileDataStore{
    //var name: String { get set }
}

class EditProfileInteractor: EditProfileBusinessLogic, EditProfileDataStore{
    var presenter: EditProfilePresentationLogic?
    var worker: EditProfileWorker?
    //var name: String = ""

    // MARK: Do something

    func doSomething(request: EditProfile.Something.Request){
        worker = EditProfileWorker()
        worker?.doSomeWork()

        let response = EditProfile.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
