//
//  LocationPresenter.swift
//  ajwa
//
//  Created by Aisaule Sibatova on 23.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationPresentationLogic {
  func presentLocation(response: [Location.ModelType.ViewModel])
}

final class LocationPresenter: LocationPresentationLogic {
    weak var viewController: LocationDisplayLogic?

    // MARK: Do something

    func presentLocation(response: [Location.ModelType.ViewModel]) {
        viewController?.displayLocation(viewModel: response)
    }
}
