//
//  LocationModels.swift
//  ajwa
//
//  Created by Aisaule Sibatova on 23.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum Location {

    enum ModelType {
        
        struct Request { }
        
        struct Response: Decodable {
            struct City: Decodable {
                let title: String
                let timezone: String
            }

            let count: Int
            var next: String?
            var previous: String?
            var results: [City]
        }

        struct ViewModel: Decodable {
            var isSelected = false
            let cityTitle: String
            var utcTimezone: String
        }
    }
}
