//
//  LocationModels.swift
//  ajwa
//
//  Created by Aisaule Sibatova on 23.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationType {
    var states: [String] { get set }

}

struct Country: LocationType {
    var states: [String]
}

struct City: LocationType, Decodable {
    var states: [String]
    var utcTimezone: String

}

enum Location
{
  // MARK: Use cases
  
  enum ModelType
  {
    struct Request
    {
    }
    struct Response
    {
    }
      struct ViewModel: Decodable
    {
//        let countries: [String]
//        var isExpanded: Bool
        
        let country: String
        let states: [String]
        var isExpanded: Bool

      
    }
  }
}
