//
//  LocationWorker.swift
//  ajwa
//
//  Created by Aisaule Sibatova on 23.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation
import Alamofire

final class CitiesWorker {
    func fetchCities(for page: Int = 0, completion: @escaping (Location.ModelType.Response) -> Void) {
        let request = AF.request("https://api.muftyat.kz/cities/?page=\(page)")

        request.responseDecodable(of: Location.ModelType.Response.self) { (result) in
            guard let cities = result.value else { return }
            completion(cities)
        }
    }
}
