//
//  NamazInteractor.swift
//  ajwa
//
//  Created by Aisaule Sibatova on 28.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NamazBusinessLogic
{
  func doSomething(request: Namaz.Something.Request)
}

protocol NamazDataStore
{
  //var name: String { get set }
}

class NamazInteractor: NamazBusinessLogic, NamazDataStore
{
  var presenter: NamazPresentationLogic?
  var worker: NamazWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Namaz.Something.Request)
  {
    worker = NamazWorker()
    worker?.doSomeWork()
    
    let response = Namaz.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
