//
//  NamazViewController.swift
//  ajwa
//
//  Created by Aisaule Sibatova on 28.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NamazDisplayLogic: AnyObject
{
  func displaySomething(viewModel: Namaz.Something.ViewModel)
}

class NamazViewController: UIViewController, NamazDisplayLogic
{
  var interactor: NamazBusinessLogic?
  var router: (NSObjectProtocol & NamazRoutingLogic & NamazDataPassing)?
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    let request = Namaz.Something.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Namaz.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
