//
//  PrayerTimeWorker.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 10.09.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class PrayerTimeWorker{
    func fetchPrayerTimes() -> [PrayerTime.ModelType.ViewModel] {
        let prayers = [
            PrayerTime.ModelType.ViewModel(prayerName: "Фаджр", isEnabled: true),
            PrayerTime.ModelType.ViewModel(prayerName: "Восход"),
            PrayerTime.ModelType.ViewModel(prayerName: "Зухр"),
            PrayerTime.ModelType.ViewModel(prayerName: "Аср"),
            PrayerTime.ModelType.ViewModel(prayerName: "Магриб"),
            PrayerTime.ModelType.ViewModel(prayerName: "Иша"),
        ]
        return prayers
    }
}
