//
//  PrayerTimeRouter.swift
//  ajwa
//
//  Created by Kuanysh al-Khattab Auyelgazy on 11.10.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PrayerTimeRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol PrayerTimeDataPassing
{
  var dataStore: PrayerTimeDataStore? { get }
}

class PrayerTimeRouter: NSObject, PrayerTimeRoutingLogic, PrayerTimeDataPassing
{
  weak var viewController: PrayerTimeViewController?
  var dataStore: PrayerTimeDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: PrayerTimeViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: PrayerTimeDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
