//
//  RegistrationSceneViewController.swift
//  ajwa
//
//  Created by ti1ek on 19.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationSceneDisplayLogic: AnyObject {
    func displaySomething(viewModel: RegistrationScene.Something.ViewModel)
}

class RegistrationSceneViewController: UIViewController, RegistrationSceneDisplayLogic {
    
    var interactor: RegistrationSceneBusinessLogic?
    var router: (NSObjectProtocol & RegistrationSceneRoutingLogic & RegistrationSceneDataPassing)?
    
    // MARK: - Outlets
    private lazy var ajwaLogoImageView: UIImageView = {
        let imageView = UIImageView()
        imageView.backgroundColor = AppColor.celeste.uiColor
        return imageView
    }()
    
    private lazy var welcomeMessageLabel: UILabel = {
        let label = UILabel()
        
        let attributedTitle = NSMutableAttributedString(string: "Добро пожаловать в ",
                                                        attributes:
                                                            [NSAttributedString.Key.font: AppFont.regular.s20(),
                                                             NSAttributedString.Key.foregroundColor: AppColor.blue.uiColor])
        
        attributedTitle.append(NSAttributedString(string: "Namaz",
                                                  attributes:
                                                    [NSAttributedString.Key.font: AppFont.semibold.s20(),
                                                     NSAttributedString.Key.foregroundColor: AppColor.blue.uiColor]))
        label.textAlignment = .center
        label.attributedText = attributedTitle
        return label
    }()
    
    private lazy var phoneNumberStackView: UIStackView = {
        let stackView = UIStackView()
        stackView.axis = .vertical
        stackView.spacing = 15
        return stackView
    }()
    
    private lazy var phoneNumberTextLabel: UILabel = {
        let label = UILabel()
        label.textColor = AppColor.black.uiColor
        label.textAlignment = .left
        label.font = AppFont.regular.s20()
        label.text = "Номер телефона"
        return label
    }()
    
    private lazy var phoneDetailsContainerView: UIView = {
        let view = UIView()
        view.backgroundColor = AppColor.celeste.uiColor
        view.layer.cornerRadius = 5
        return view
    }()
    
    private lazy var countryCodeLabel: UILabel = {
        let label = UILabel()
        label.text = "KZ +7"
        label.textColor = AppColor.black.uiColor
        label.font = AppFont.regular.s16()
        return label
    }()
    
    private lazy var phoneNumberTextField: UITextField = {
        let textField = UITextField()
        textField.font = AppFont.regular.s16()
        textField.attributedPlaceholder = NSAttributedString(
            string: "(_ _ _) _ _ _ - _ _ - _ _",
            attributes: [NSAttributedString.Key.foregroundColor: AppColor.blue.uiColor]
        )
        textField.textColor = .black
        textField.keyboardType = .phonePad
        textField.autocorrectionType = .no
        return textField
    }()
    
    private lazy var alreadyHaveAccountButton: UIButton = {
        let button = UIButton(type: .system)
        let attributedTitle = NSMutableAttributedString(string: "У вас уже есть аккаунт? ",
                                                        attributes:
                                                            [NSAttributedString.Key.font:
                                                                AppFont.regular.s16(),
                                                             NSAttributedString.Key.foregroundColor: AppColor.darkGray.uiColor])
        
        attributedTitle.append(NSAttributedString(string: "Войти",
                                                  attributes:
                                                    [NSAttributedString.Key.font: AppFont.regular.s16(),
                                                     NSAttributedString.Key.foregroundColor: AppColor.lightBlue.uiColor,
                                                     NSAttributedString.Key.underlineStyle: NSUnderlineStyle.single.rawValue
                                                    ]))
        
        button.addTarget(self, action: #selector(handleShowLogin), for: .touchUpInside)
        button.setAttributedTitle(attributedTitle, for: .normal)
        return button
    }()
    
    
    // MARK: View lifecycle
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        ajwaLogoImageView.layer.cornerRadius = ajwaLogoImageView.frame.size.width / 2
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
        
        setupUI()
        setupConstraints()
    }
    
    // MARK: - UI Setup
    private func setupUI() {
        view.backgroundColor = .white
        view.addSubview(ajwaLogoImageView)
        view.addSubview(welcomeMessageLabel)
        view.addSubview(phoneNumberStackView)
        phoneNumberStackView.addArrangedSubview(phoneNumberTextLabel)
        phoneNumberStackView.addArrangedSubview(phoneDetailsContainerView)
        phoneDetailsContainerView.addSubview(countryCodeLabel)
        phoneDetailsContainerView.addSubview(phoneNumberTextField)
        view.addSubview(alreadyHaveAccountButton)
    }
    
    // MARK: - Constraints Setup
    private func setupConstraints() {
        ajwaLogoImageView.snp.makeConstraints { make in
            make.top.equalTo(view.safeAreaLayoutGuide.snp.topMargin).offset(130)
            make.leading.equalToSuperview().offset(130)
            make.trailing.equalToSuperview().inset(130)
            make.height.equalTo(ajwaLogoImageView.snp.width)
        }
        
        welcomeMessageLabel.snp.makeConstraints { make in
            make.top.equalTo(ajwaLogoImageView.snp.bottom).offset(30)
            make.leading.equalToSuperview().offset(30)
            make.trailing.equalToSuperview().inset(30)
        }
        
        phoneNumberStackView.snp.makeConstraints { make in
            make.top.equalTo(welcomeMessageLabel.snp.bottom).offset(58)
            make.leading.equalToSuperview().offset(20)
            make.trailing.equalToSuperview().inset(20)
        }
        
        countryCodeLabel.snp.makeConstraints { make in
            make.leading.equalToSuperview().offset(15)
            make.top.bottom.equalToSuperview().inset(15)
        }
        
        phoneNumberTextField.snp.makeConstraints { make in
            make.leading.equalTo(countryCodeLabel.snp.trailing).offset(5)
            make.top.bottom.equalToSuperview().inset(15)
        }
        alreadyHaveAccountButton.snp.makeConstraints { make in
            make.leading.equalToSuperview().offset(20)
            make.trailing.equalToSuperview().inset(20)
            make.top.equalTo(phoneDetailsContainerView.snp.bottom).offset(20)
        }
    }
    
    // MARK: - Actions
    @objc func handleShowLogin() {
    }
    
    // MARK: Do something
    func doSomething() {
        let request = RegistrationScene.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: RegistrationScene.Something.ViewModel) {
    }
}
