//
//  RegistrationSceneConfigurator.swift
//  ajwa
//
//  Created by ti1ek on 19.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RegistrationSceneConfigurator {
    
    static let shared = RegistrationSceneConfigurator()
    
    func configure(viewController: RegistrationSceneViewController) {
        let interactor = RegistrationSceneInteractor()
        let presenter = RegistrationScenePresenter()
        let router = RegistrationSceneRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
    }
}
