//
//  RegistrationSceneInteractor.swift
//  ajwa
//
//  Created by ti1ek on 19.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationSceneBusinessLogic
{
  func doSomething(request: RegistrationScene.Something.Request)
}

protocol RegistrationSceneDataStore
{
  //var name: String { get set }
}

class RegistrationSceneInteractor: RegistrationSceneBusinessLogic, RegistrationSceneDataStore
{
  var presenter: RegistrationScenePresentationLogic?
  var worker: RegistrationSceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RegistrationScene.Something.Request)
  {
    worker = RegistrationSceneWorker()
    worker?.doSomeWork()
    
    let response = RegistrationScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
