//
//  RegistrationScenePresenter.swift
//  ajwa
//
//  Created by ti1ek on 19.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationScenePresentationLogic
{
  func presentSomething(response: RegistrationScene.Something.Response)
}

class RegistrationScenePresenter: RegistrationScenePresentationLogic
{
  weak var viewController: RegistrationSceneDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: RegistrationScene.Something.Response)
  {
    let viewModel = RegistrationScene.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
