//
//  NameEntrySceneInteractor.swift
//  ajwa
//
//  Created by ti1ek on 20.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NameEntrySceneBusinessLogic
{
  func doSomething(request: NameEntryScene.Something.Request)
}

protocol NameEntrySceneDataStore
{
  //var name: String { get set }
}

class NameEntrySceneInteractor: NameEntrySceneBusinessLogic, NameEntrySceneDataStore
{
  var presenter: NameEntryScenePresentationLogic?
  var worker: NameEntrySceneWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: NameEntryScene.Something.Request)
  {
    worker = NameEntrySceneWorker()
    worker?.doSomeWork()
    
    let response = NameEntryScene.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
