//
//  NameEntrySceneConfigurator.swift
//  ajwa
//
//  Created by ti1ek on 20.08.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class NameEntrySceneConfigurator {
    
    static let shared = NameEntrySceneConfigurator()
    
    func configure(viewController: NameEntrySceneViewController) {
        let interactor = NameEntrySceneInteractor()
        let presenter = NameEntryScenePresenter()
        let router = NameEntrySceneRouter()
        
        viewController.interactor = interactor
        viewController.router = router
        
        interactor.presenter = presenter
        presenter.viewController = viewController
        
        router.viewController = viewController
        router.dataStore = interactor
    }
}
